services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: aseed-zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      # Automatyczne czyszczenie starych sesji
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      # Krótszy czas sesji - szybsze wykrywanie rozłączeń
      ZOOKEEPER_MAX_SESSION_TIMEOUT: 10000
      # Czyszczenie snapshot'ów
      ZOOKEEPER_AUTOPURGE_PURGEINTERVAL: 1
      ZOOKEEPER_AUTOPURGE_SNAPRETAINCOUNT: 3
    networks:
      - aseed-network
    volumes:
      - ./logs:/logs
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
      - confluent-cache:/etc/confluent
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "
        # Utwórz plik logu z odpowiednimi uprawnieniami
        touch /logs/zookeeper.log && chmod 666 /logs/zookeeper.log
        
        echo 'Uruchamiam ZooKeeper...' | tee -a /logs/zookeeper.log
        
        # Uruchom Zookeeper z przekierowaniem logów (usuń kody kolorów)
        /etc/confluent/docker/run 2>&1 | sed -u 's/\x1b\[[0-9;]*[mGKHF]//g' | tee -a /logs/zookeeper.log
      "
    healthcheck:
      test: ["CMD", "sh", "-c", "echo 'srvr' | nc localhost 2181 | grep -q 'Mode'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: aseed-kafka
    restart: unless-stopped
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      # Konfiguracja dla czystego startu
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LOG_CLEANUP_POLICY: delete
      KAFKA_LOG_RETENTION_HOURS: 1
      # Timeout dla ZooKeeper - szybsze wykrywanie problemów
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 6000
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 6000
    networks:
      - aseed-network
    volumes:
      - ./logs:/logs
      - kafka-data:/var/lib/kafka/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "
        # Utwórz plik logu z odpowiednimi uprawnieniami
        touch /logs/kafka.log && chmod 666 /logs/kafka.log
        
        echo 'Czekanie na gotowość ZooKeeper...' | tee -a /logs/kafka.log
        
        # Poczekaj na ZooKeeper (używając srvr zamiast ruok)
        until echo 'srvr' | nc zookeeper 2181 | grep -q 'Mode'; do
          echo 'ZooKeeper nie jest gotowy, czekanie 3s...' | tee -a /logs/kafka.log
          sleep 3
        done
        
        echo 'ZooKeeper jest gotowy, uruchamiam Kafka...' | tee -a /logs/kafka.log
        
        # Uruchom Kafka z przekierowaniem logów (usuń kody kolorów)
        /etc/confluent/docker/run 2>&1 | sed -u 's/\x1b\[[0-9;]*[mGKHF]//g' | tee -a /logs/kafka.log
      "
    healthcheck:
      test: ["CMD", "sh", "-c", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s

  # Init kontener do sprawdzania stanu ZooKeeper/Kafka
  kafka-init:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - aseed-network
    volumes:
      - ./logs:/logs
    command: >
      sh -c "
        echo 'Sprawdzanie gotowości Kafka...' | tee -a /logs/kafka-init.log
        
        # Sprawdź czy Kafka jest gotowa
        until kafka-broker-api-versions --bootstrap-server kafka:9092; do
          echo 'Kafka nie jest gotowa, czekanie 5s...' | tee -a /logs/kafka-init.log
          sleep 5
        done
        
        echo 'Kafka jest gotowa!' | tee -a /logs/kafka-init.log
        
        # Utworzenie podstawowych topików jeśli nie istnieją
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic orders --partitions 1 --replication-factor 1 || true
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic processed-orders --partitions 1 --replication-factor 1 || true
        
        echo 'Kafka init zakończony pomyślnie' | tee -a /logs/kafka-init.log
      "

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    hostname: spark-master
    container_name: aseed-spark-master
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    networks:
      - aseed-network
    volumes:
      - ./src:/opt/spark-apps
      - ./logs:/logs
      - spark-ivy-cache:/home/spark/.ivy2
      - maven-cache:/root/.m2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "
        # Utwórz plik logu
        touch /logs/spark-master.log
        
        # Ustaw zmienne środowiskowe dla Spark
        export SPARK_NO_DAEMONIZE=true
        export SPARK_LOG_LEVEL=INFO
        export NO_COLOR=1
        export TERM=dumb
        
        # Uruchom Spark Master z poprawnym filtrowaniem ANSI
        /opt/bitnami/scripts/spark/entrypoint.sh /opt/bitnami/scripts/spark/run.sh 2>&1 | 
        sed -u 's/\x1b\[[0-9;]*[mGKHF]//g' | 
        tee -a /logs/spark-master.log
      "
    healthcheck:
      test: ["CMD", "python3", "-c", "import socket; socket.create_connection(('localhost', 8080), timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.spark
    hostname: spark-worker
    container_name: aseed-spark-worker
    restart: unless-stopped
    depends_on:
      spark-master:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_HOST=spark-worker
    networks:
      - aseed-network
    volumes:
      - ./src:/opt/spark-apps
      - ./logs:/logs
      - spark-ivy-cache:/home/spark/.ivy2
      - maven-cache:/root/.m2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "
        # Utwórz plik logu
        touch /logs/spark-worker.log
        
        # Ustaw zmienne środowiskowe dla Spark
        export SPARK_NO_DAEMONIZE=true
        export SPARK_LOG_LEVEL=INFO
        export NO_COLOR=1
        export TERM=dumb
        
        # Uruchom Spark Worker z poprawnym filtrowaniem ANSI
        /opt/bitnami/scripts/spark/entrypoint.sh /opt/bitnami/scripts/spark/run.sh 2>&1 | 
        sed -u 's/\x1b\[[0-9;]*[mGKHF]//g' | 
        tee -a /logs/spark-worker.log
      "

  order-simulator:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: aseed-order-simulator
    restart: unless-stopped
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=orders
      - ORDERS_PER_SECOND=2
      - PRODUCT_COUNT=50
    networks:
      - aseed-network
    volumes:
      - ./logs:/app/logs
      - pip-cache:/root/.cache/pip
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "
        # Utwórz plik logu
        touch /app/logs/order_simulator.log
        
        # Uruchom simulator z przekierowaniem logów (usuń kody kolorów)
        python src/order_simulator.py 2>&1 | sed 's/\x1b\[[0-9;]*m//g' | tee -a /app/logs/order_simulator.log
      "

  data-analyzer:
    build:
      context: .
      dockerfile: Dockerfile.spark-app
    container_name: aseed-data-analyzer
    restart: unless-stopped
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      spark-master:
        condition: service_healthy
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - aseed-network
    volumes:
      - ./src:/opt/spark-apps
      - ./logs:/logs
      - spark-ivy-cache:/home/spark/.ivy2
      - maven-cache:/root/.m2
      - pip-cache:/root/.cache/pip
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "
        # Utwórz plik logu
        touch /logs/data_analyzer.log
        
        # Uruchom analyzer z przekierowaniem logów (usuń kody kolorów)
        python /opt/spark-apps/data_analyzer.py 2>&1 | sed 's/\x1b\[[0-9;]*m//g' | tee -a /logs/data_analyzer.log
      "
    healthcheck:
      test: ["CMD", "pgrep", "-f", "data_analyzer.py"]
      interval: 30s
      timeout: 10s
      retries: 3

  web-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: aseed-web-dashboard
    restart: unless-stopped
    ports:
      - "5005:5005"
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - FLASK_ENV=production
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5005
    networks:
      - aseed-network
    volumes:
      - ./logs:/app/logs
      - ./src/templates:/app/src/templates
      - /var/run/docker.sock:/var/run/docker.sock
      - pip-cache:/root/.cache/pip
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "
        # Utwórz plik logu
        touch /app/logs/dashboard.log
        
        # Ustaw zmienne środowiskowe dla Flask bez kolorów
        export FLASK_ENV=production
        export PYTHONUNBUFFERED=1
        export NO_COLOR=1
        export TERM=dumb
        unset WERKZEUG_SERVER_FD
        
        # Uruchom dashboard z precyzyjnym filtrowaniem ANSI
        python src/web_dashboard.py 2>&1 | 
        sed -u 's/\x1b\[[0-9;]*[mGKHF]//g' | 
        tee -a /app/logs/dashboard.log
      "

networks:
  aseed-network:
    driver: bridge

volumes:
  # Data volumes
  kafka-data:
  zookeeper-data:
  zookeeper-logs:
  
  # Cache volumes to dramatically speed up container startup
  maven-cache:
  spark-ivy-cache:
  pip-cache:
  confluent-cache:
